export const ADMIN_PATHS = {
  DASHBOARD: "dashboard",
  ROOM_LIST: "room-list",
  ROOM_CREATE: "room-list/create",
  ROOM_TYPE: "room-type",
  ROOM_TYPE_CREATE: "room-type/create",
  ROOM_AMENITIES: "room-amenities",
  ROOM_AMENITY_CREATE: "room-amenities/create",
  BOOKINGS: "bookings",
  BOOKING_CREATE: "bookings/create",
  EMPLOYEES: "employees",
  ROLES: "roles",
  CUSTOMERS: "customers",
  CUSTOMER_CREATE:"customers/create",
  SERVICES: "services",
  SERVICE_USAGE: "service-usage",
  INVENTORY: "inventory",
  INVENTORY_HISTORY: "inventory-history",
  REPORT_SUMMARY: "report-summary",
  REPORT_SERVICE_REVENUE: "report-service-revenue",
  REPORT_BILL_REVENUE: "report-bill-revenue",
  INVOICES: "invoices",
  HOTEL_SETTING: "hotel-setting",
};
